[package]
name = "bpv"
version = "0.1.0"
authors = ["yucklys"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.9"
dirs = "*"
structopt = "0.3"
regex = "1"
flate2 = "1.0"
